daysUntilStale: 365

staleLabel: stale

markComment: >
  Hi, ${{ github }},
  This pr/issue has been automatically marked as stale because it has not had recent activity.
  It will be closed if no further activity occurs for 7 more days. Thank you for your contributions.